server:
  port: 8196
# Mysql数据库
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/spot?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&stringtype=unspecified&currentSchema=public
    username: postgres
    password: 1qaz2wsx
    filters: mergeStat
  redis:
    host: localhost
    port: 16379
    password: 1qaz2wsx
    # 连接超时时间（毫秒）
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

  # 邮件发送配置（改为自己的账号和密码）
  mail:
    host: smtp.qq.com
    port: 587
    username: sn93@qq.com
    password: xxxpassword

# 邮件发送（改为自己的账号）
mail:
  from: sn93@qq.com

